// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxhxhztskozxgiylygye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4aHhoenRza296eGdpeWx5Z3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MzAwNDUsImV4cCI6MjA1MjIwNjA0NX0.1x_yu4jx3G9QqyCeQfrZKXLFD_c0eHNQ0J1Pi-5i-cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);